[package]
name = "ironrdp-tokio"
version = "0.2.1"
readme = "README.md"
description = "`Framed*` traits implementation above Tokioâ€™s traits"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
bytes = "1"
ironrdp-async.workspace = true
tokio = { version = "1", features = ["io-util"] }

[lints]
workspace = true

