[package]
name = "ironrdp-tokio"
version = "0.3.1"
readme = "README.md"
description = "`Framed*` traits implementation above Tokioâ€™s traits"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest", "dep:sspi", "dep:url"]

[dependencies]
bytes = "1"
ironrdp-async = { path = "../ironrdp-async", version = "0.4" } # public
tokio = { version = "1", features = ["io-util"] }
reqwest = { version = "0.12", optional = true }
sspi = { version = "0.15", features = [
    "network_client",
    "dns_resolver",
], optional = true } # TODO: enable additional features
url = { version = "2.5", optional = true }

[lints]
workspace = true
