[package]
name = "ironrdp-fuzzing"
version = "0.0.0"
edition = "2021"
description = "Provides test case generators and oracles for use with IronRDP fuzzing"
publish = false

[lib]
doctest = false
test = false

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
ironrdp-core.workspace = true
ironrdp-graphics.workspace = true
ironrdp-pdu.workspace = true
ironrdp-cliprdr.workspace = true
ironrdp-rdpdr.workspace = true
ironrdp-rdpsnd.workspace = true
ironrdp-cliprdr-format.workspace = true
ironrdp-displaycontrol.workspace = true
ironrdp-egfx.workspace = true
ironrdp-svc.workspace = true

[lints]
workspace = true

