[package]
name = "ironrdp-displaycontrol"
version = "0.2.0"
readme = "README.md"
description = "Display control dynamic channel extension implementation"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.1" } # public
ironrdp-dvc = { path = "../ironrdp-dvc", version = "0.2" } # public
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.5" } # public
ironrdp-svc = { path = "../ironrdp-svc", version = "0.3" } # public
tracing = { version = "0.1", features = ["log"] }

[lints]
workspace = true
