[package]
name = "ironrdp-session"
version = "0.1.0"
readme = "README.md"
description = "State machines to drive an RDP session"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
bitflags = "2" # TODO: investigate usage in this crate
ironrdp-connector.workspace = true # TODO: at some point, this dependency could be removed (good for compilation speed)
ironrdp-svc.workspace = true
ironrdp-dvc.workspace = true
ironrdp-error.workspace = true
ironrdp-graphics.workspace = true
ironrdp-pdu = { workspace = true, features = ["std"] }
sspi.workspace = true
tracing.workspace = true
