[package]
name = "ironrdp-session"
version = "0.8.0"
readme = "README.md"
description = "State machines to drive an RDP session"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[features]
default = []
qoi = ["dep:qoicoubeh", "ironrdp-pdu/qoi"]
qoiz = ["dep:zstd-safe", "qoi"]

[dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.1" } # public
ironrdp-connector = { path = "../ironrdp-connector", version = "0.8" } # public # TODO: at some point, this dependency could be removed (good for compilation speed)
ironrdp-svc = { path = "../ironrdp-svc", version = "0.5" } # public
ironrdp-dvc = { path = "../ironrdp-dvc", version = "0.4" } # public
ironrdp-error = { path = "../ironrdp-error", version = "0.1" } # public
ironrdp-graphics = { path = "../ironrdp-graphics", version = "0.7" } # public
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.6", features = ["std"] } # public
ironrdp-displaycontrol = { path = "../ironrdp-displaycontrol", version = "0.4" }
tracing = { version = "0.1", features = ["log"] }
qoicoubeh = { version = "0.5", optional = true }
zstd-safe = { version = "7.2", optional = true, features = ["std"] }

[lints]
workspace = true
