[workspace]
dependencies_update = true
git_release_enable = false
semver_check = true
pr_branch_prefix = "release-plz/"
pr_name = "chore(release): prepare for publishing"
changelog_config = "cliff.toml"
release_commits = "^(feat|docs|fix|build|perf)"

# Flagship crate for which we push a GitHub release.
[[package]]
name = "ironrdp-client"
git_release_enable = true
publish = false # TODO: enable publishing when ready.

# ironrdp-tls does not compile if no backend is specified.
# rustls is the most common backend, so we let cargo publish check with it.
[[package]]
name = "ironrdp-tls"
publish_features = ["rustls"]

# *-native crates may have all kinds of system requirements depending on the platform.
# We can only check for the current platform when cargo publish is invoked, all the others are effectively unverified.
# For this reason, it's not worth complexifying the release-crates.yml workflow.
# We already verify all targets properly in the regular CI workflow.
[[package]]
name = "ironrdp-rdpdr-native"
publish_no_verify = true
[[package]]
name = "ironrdp-rdpsnd-native"
publish_no_verify = true
[[package]]
name = "ironrdp-cliprdr-native"
publish_no_verify = true

[changelog]
protect_breaking_commits = true # Always include commits with breaking changes in the changelog.
