[package]
name = "ironrdp"
version = "0.4.1"
edition = "2018"
readme = "../README.md"
license = "MIT/Apache-2.0"
homepage = "https://github.com/Devolutions/IronRDP"
repository = "https://github.com/Devolutions/IronRDP"
authors = ["Marc-Andr√© Moreau <mamoreau@devolutions.net>",
           "Vlad Aleksashyn <vlad.al.dp@gmail.com"]
description = "A Rust implementation of the Microsoft Remote Desktop Protocol"
keywords = ["rdp", "remote", "desktop", "protocol"]

[dependencies]
byteorder = "1.3"
bitflags = "1.2"
num-derive = "0.3"
num-traits = "0.2"
lazy_static = "1.4"
bytes = "0.5"
num-integer = "0.1"
failure = "0.1"
x509-parser = "0.6.0"
ring = "0.16.0"
md-5 = "0.8.0"
num-bigint = "0.2.0"
der-parser = "3.0.0"
bit_field = "0.10"
bitvec = "0.17.1"
hex-literal = "0.2"
