[package]
name = "ironrdp-graphics"
version = "0.1.0"
readme = "README.md"
description = "RDP image processing primitives"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
# test = false

[dependencies]
bit_field = "0.10"
bitflags.workspace = true
bitvec = "1.0"
byteorder.workspace = true
ironrdp-error.workspace = true
ironrdp-pdu = { workspace = true, features = ["std"] }
lazy_static = "1.4"
num-derive.workspace = true
num-traits.workspace = true
thiserror.workspace = true

[dev-dependencies]
bmp = "0.5"
expect-test.workspace = true
