[package]
name = "ironrdp-graphics"
version = "0.3.0"
readme = "README.md"
description = "RDP image processing primitives"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
# test = false

[dependencies]
bit_field = "0.10"
bitflags = "2.4"
bitvec = "1.0"
ironrdp-core = { path = "../ironrdp-core", version = "0.1" } # public
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.4", features = ["std"] } # public
byteorder = "1.5" # TODO: remove
lazy_static.workspace = true # Legacy crate; prefer std::sync::LazyLock or LazyCell
num-derive.workspace = true # TODO: remove
num-traits.workspace = true # TODO: remove
thiserror = "2" # FIXME: handwrite the Error trait implementations.
yuv = { version = "0.8", features = ["rdp"] }

[dev-dependencies]
bmp = "0.5"
bytemuck = "1.21"
expect-test.workspace = true

[lints]
workspace = true

