[package]
name = "ironrdp-graphics"
version = "0.1.1"
readme = "README.md"
description = "RDP image processing primitives"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
# test = false

[dependencies]
bit_field = "0.10"
bitflags.workspace = true
bitvec = "1.0"
byteorder.workspace = true # TODO: remove
ironrdp-core.workspace = true
ironrdp-pdu = { workspace = true, features = ["std"] }
lazy_static.workspace = true # TODO: remove in favor of https://doc.rust-lang.org/std/sync/struct.OnceLock.html
num-derive.workspace = true # TODO: remove
num-traits.workspace = true # TODO: remove
thiserror.workspace = true

[dev-dependencies]
bmp = "0.5"
expect-test.workspace = true

[lints]
workspace = true

