[package]
name = "ironrdp-rdpdr"
version = "0.1.0"
readme = "README.md"
description = "RDPDR channel implementation."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
tracing.workspace = true
ironrdp-pdu.workspace = true
ironrdp-svc.workspace = true
ironrdp-error.workspace = true

bitflags = "2"
