[package]
name = "ironrdp-rdpdr"
version = "0.2.0"
readme = "README.md"
description = "RDPDR channel implementation."
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.1" } # public
ironrdp-error = { path = "../ironrdp-error", version = "0.1" } # public
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.4" } # public
ironrdp-svc = { path = "../ironrdp-svc", version = "0.3" } # public
tracing = { version = "0.1", features = ["log"] }
bitflags = "2.4"

[lints]
workspace = true
