[package]
name = "ironrdp-futures"
version = "0.4.0"
readme = "README.md"
description = "`Framed*` traits implementation above futuresâ€™s traits"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
futures-util = { version = "0.3", features = ["io"] } # public
ironrdp-async = { path = "../ironrdp-async", version = "0.7" } # public
bytes = "1" # public

[lints]
workspace = true

