[package]
name = "ironrdp-futures"
version = "0.1.0"
readme = "README.md"
description = "`Framed*` traits implementation above futuresâ€™s traits"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bytes = "1"
futures-util = { version = "0.3.26", features = ["io"] }
ironrdp-async.workspace = true
