[package]
name = "ironrdp-input"
version = "0.6.0"
readme = "README.md"
description = "Utilities to manage and build RDP input packets"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.6" } # public
bitvec = "1.0"
smallvec = "1.15"

[lints]
workspace = true

