[package]
name = "ironrdp-cliprdr-format"
version = "0.1.3"
readme = "README.md"
description = "CLIPRDR format conversion library"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.1" } # public
thiserror = "2" # FIXME: handwrite the Error trait implementations.
png = "0.17"

[lints]
workspace = true

