[package]
name = "ironrdp-dvc-com-plugin"
version = "0.1.0"
readme = "README.md"
description = "DVC COM client plugin loader for IronRDP (Windows)"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]

[target.'cfg(windows)'.dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.1" }
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.7" }
ironrdp-dvc = { path = "../ironrdp-dvc", version = "0.5" }
ironrdp-svc = { path = "../ironrdp-svc", version = "0.6" }
tracing = { version = "0.1", features = ["log"] }
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_System_RemoteDesktop",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_LibraryLoader",
] }
windows-core = "0.62"

[lints]
workspace = true
