[package]
name = "ironrdp-wtsprotocol-provider"
version = "0.1.0"
readme = "README.md"
description = "Windows Remote Desktop Services protocol provider backed by IronRDP"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false
test = false

[dependencies]
tracing = { version = "0.1", features = ["log"] }
parking_lot = "0.12"

[target.'cfg(windows)'.dependencies]
ironrdp-acceptor = { path = "../ironrdp-acceptor", version = "0.8" }
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.7" }
ironrdp-connector = { path = "../ironrdp-connector", version = "0.8" }
ironrdp-wtsprotocol-ipc = { path = "../ironrdp-wtsprotocol-ipc", version = "0.1" }
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Com_Marshal",
    "Win32_System_Pipes",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_RemoteDesktop",
] }
windows-core = "0.62"

[lints]
workspace = true
